import type { Metadata } from "next";
import { Inter, Fredoka } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import AuthSync from "@/components/AuthSync";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-body",
  display: "swap",
});

const fredoka = Fredoka({
  subsets: ["latin"],
  variable: "--font-display",
  display: "swap",
});

export const metadata: Metadata = {
  title: "GraphiDraw",
  description: "Generated by create next app",
  icons: {
    icon: "/icon.svg",
    shortcut: "/icon.svg",
    apple: "/icon.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${inter.variable} ${fredoka.variable} antialiased`}>
          <AuthSync />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
